id: IDDDBB3D7
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T08:06:38+00:00'
last_modified: '2022-06-08T10:37:53.599847+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG13836
  title: བཀའ་གཏེར་གཉིས་འདུས་སྨིན་གླིང་རྡོར་སེམས་ཀྱི་སྒྲུབ་སྐོར་ཆོས་ཚན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    07B2:
      image_group_id: I1KG16123
      title: ''
      total_pages: 264
      order: 1
      base_file: 07B2.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
