id: P009384
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-19 19:36:15.376050
source_metadata:
  id: bdr:W1KG13836
  title: བཀའ་གཏེར་གཉིས་འདུས་སྨིན་གླིང་རྡོར་སེམས་ཀྱི་སྒྲུབ་སྐོར་ཆོས་ཚན།
  author: ''
  volumes:
    360a40fb6dc646b58311790ca47976a0:
      image_group_id: I1KG16123
      title: ''
      volume_number: 1
      total_pages: 264
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
